listView('hello-view') {
    jobs {
        name('hello-job')
    }
    columns {
        buildButton()
        buildParameters()
        categorizedJob()
        claim()
        configureProject()
        cronTrigger()
        customIcon()
        disableProject()
        jacoco()
        lastBuildConsole()
        lastBuildNode()
        lastConfigurationModification()
        lastDuration()
        lastFailure()
        lastSuccess()
        name()
        nextLaunch()
        nextPossibleLaunch()
        progressBar()
        releaseButton()
        robotResults()
        scmType()
        slaveOrLabel()
        status()
        testResult()
        userName()
        weather()
        workspace()
    }
}
